name: Gatsby Publish

on:
  push:
    branches:
      - site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Prepare documentation markdown files
      #   run: ./prepare-docs.sh
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
